hl.on("hyprland.start", function () 
   hl.exec_cmd("nm-applet --indicator")
   hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland")
   hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
   hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
   hl.exec_cmd("fcitx5 -d")
   hl.exec_cmd("env QML_XHR_ALLOW_FILE_READ=1 qs")
   hl.exec_cmd("awww-daemon")
   hl.exec_cmd("blueman-applet")
   hl.exec_cmd("easyeffects --gapplication-service")
   hl.exec_cmd("udiskie --automount --notify")
 end)
