# ~/.config/hypr/modules/environment.conf

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# IME (fcitx5)
env = QT_IM_MODULE,fcitx
env = XMODIFIERS,@im=fcitx
env = INPUT_METHOD,fcitx
env = GTK_IM_MODULE,fcitx

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_STYLE_OVERRIDE,kvantum
env = XDG_DATA_DIRS,/usr/local/share:/usr/share
