windowrulev = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

windowrule = match:class ^steam_app_.*, fullscreen 1 
windowrule = match:class ^steam_app_.*, immediate 1
windowrule = match:class kitty, match:focus 1, opaque 1
windowrule = match:class kitty, no_blur 1
windowrule = match:class gimp, match:focus 1, opaque 1
windowrule = match:class gimp, no_blur 1
windowrule = match:title ^Picture-in-Picture$, float 1 
windowrule = match:title ^Picture-in-Picture$, move 1280 720
windowrule = match:title ^Picture-in-Picture$, size 480 270
windowrule = match:title ^Picture-in-Picture$, keep_aspect_ratio 1

windowrule = match:title ^quickshell-powermenu$, fullscreen 1
windowrule = match:title ^quickshell-powermenu$, stay_focused 1
