# Kimi light inspired

background #f4f6f8
foreground #2e3440
selection_background #cdd6e3
selection_foreground #000000

cursor #5e81ac
cursor_text_color #f4f6f8

# Black
color0  #3b4252
color8  #4c566a

# Red
color1  #d57780
color9  #e0858e

# Green
color2  #8fbc8f
color10 #a3d9a5

# Yellow
color3  #ebcb8b
color11 #f2d399

# Blue
color4  #81a1c1
color12 #90b4d8

# Magenta
color5  #b48ead
color13 #c8a2c8

# Cyan
color6  #88c0d0
color14 #9ad1e0

# White
color7  #e5e9f0
color15 #eceff4
